### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [wametsol/FSHT#2]
# Katselmointi

Terve @wametsol! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröidyin uutena käyttäjänä
- Lisäsin uuden järjestelmän
- Lisäsin uudelle järjestelmälleni palvelun ja resurssin
- Muokkasin ajanhallintaa
- Muokkasin näkymiä
- Muokkasin yhteystietoja
- Julkaisin sivustoni
- Kirjauduin ulos
- Siirryin järjestelmäni sivustolle
- Tein varauksen
- Kirjauduin sisään ja selasin varauksia
- Kirjauduin ulos

### Kokemus

- Tyylikäs ja helppokäyttöinen käyttöliittymä, hyvää työtä! 🏆
- Järjestelmän luonti vaiheittain on erittäin kätevää
- Sivuston visuaaliseen ilmeen muokkaaminen on erinomainen toiminallisuus
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Yhteystietojen muokkauksen jälkeen tulee virheilmoitus "Tapahtui odottomaton virhe", vaikka muokkaus vaikuttaa onnistuneen. Tämä viesti löytyi konsolista: `FirebaseError: Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field publicInformation.address)`
- Kun järjestelmän sivustolta valitsee palvelun, sovellus kaatuu ja konsoliin ilmestyy tämä viesti: `TypeError: Cannot read property 'weekDays' of undefined`. Kyseessä on varmasti jokin erityistapaus, koska varauksen luonti toimii kuitenkin moitteettomasti esimerkkisivustolla

## Koodi

- Koodi on selkeästi organisoitua, hyvä!
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- Firebasen datan hakuun liittyviä operaatioita voisi abstraktoida esim. hookien avulla. [Tämän](https://github.com/wametsol/FSHT/blob/master/booking-app/src/components/BookingPage/BookingPage.js#L59) tyyppisissä haussa voisi käyttää esim. `useBooker` ja `useBookings` hookeja. Hyvin abstraktioiden avulla datan hausta tulee uudelleen käytettävää ja komponenttien koodi selkeytyy huomattavasti
- Asynkronisissa operaatioissa, joissa tehdään jatkuvasti `setLoading(true)` ja `setLoading(false)` tyyppistä tilanhallintaa voisi harkita käyttää myös jotain hook-abstraktiota, kuten [SWR](https://github.com/vercel/swr)- tai [React Async](https://react-async.dev/)-kirjastoa

## Kokonaisuus

- Hyödyllinen ja käyttäjäystävällinen sovellus, joka toimii moitteettomasti paria bugia lukuunottamatta
- Koodi on selkeästi organisoitua ja suurimmilta osin helppolukuista. Komponentteissa on jonkin verran raskasta sovelluslogiikkaa, kuten datan hakua, jonka voisi abstraktoida esim. hookien avulla

**Comment by wametsol** [comment]
Kiitokset katselmoinnista ja palautteesta!

Firebase oli itselle täysin uusi työkalu, joten sen kanssa touhuaminen on aiheuttanut enemmän päänvaivaa kuin oletin. Ohjelmaan tuli toteutettua hieman alkuperäistä suunnitelmaa enemmän toiminallisuuksia, minkä johdosta koodin refaktorointi ja juuri tuo hookien laajempi käyttö jäi tekemättä. Tarkoituksena onkin toteuttaa tuo heti kun vain ehdin.

-W
